[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/jonathan"
  to = "https://us02web.zoom.us/j/6202114445?pwd=ODFjK1pwekxISUlCMFNSN3U1OFpWdz09"
  status = 301
  force = true
