[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/jonathan"
  to = "https://us02web.zoom.us/j/6202114445?pwd=ODFjK1pwekxISUlCMFNSN3U1OFpWdz09"
  status = 301

[[redirects]]
  from = "/Jonathan"
  to = "https://us02web.zoom.us/j/6202114445?pwd=ODFjK1pwekxISUlCMFNSN3U1OFpWdz09"
  status = 301
  force = true

[[redirects]]
  from = "/emary"
  to = "https://us02web.zoom.us/j/5778694275?pwd=cnFXK2xGMW94WEtudis2SEcwWmh6UT09"
  status = 301
  force = true

[[redirects]]
  from = "/david"
  to = "https://us02web.zoom.us/j/4219501679?pwd=N0QxcVJzYWUwVk53Y1I3K2pKbHlDUT09"
  status = 301
  force = true

[[redirects]]
  from = "/blake"
  to = "https://us02web.zoom.us/j/7180208207?pwd=WWV3THZCRDRoS255THFxVEk0WFBWdz09"
  status = 301
  force = true

[[redirects]]
  from = "/casey"
  to = "https://us02web.zoom.us/j/6363552253?pwd=dS9UZm1rUmlwWlU5a0ViM3lOQTNSUT09"
  status = 301
  force = true

[[redirects]]
  from = "/Casey"
  to = "https://us02web.zoom.us/j/6363552253?pwd=dS9UZm1rUmlwWlU5a0ViM3lOQTNSUT09"
  status = 301
  force = true

[[redirects]]
  from = "/casey"
  to = "https://us02web.zoom.us/j/8241022627?pwd=VsFQuZSDQW7LT4KGaGsCC5fhaBJumN.1"
  status = 301
  force = true

[[redirects]]
  from = "/jessica"
  to = "https://us02web.zoom.us/j/8059333957?pwd=cHdsMk1sUEhCbXFnbmZFcENLQVVzUT09"
  status = 301
  force = true

[[redirects]]
  from = "/Lynnette"
  to = "https://us02web.zoom.us/j/3805633903?pwd=Um5OOWpuUnQwbCtuTHFRanRIZ1RQdz09"
  status = 301
  force = true

[[redirects]]
  from = "/lynnette"
  to = "https://us02web.zoom.us/j/3805633903?pwd=Um5OOWpuUnQwbCtuTHFRanRIZ1RQdz09"
  status = 301
  force = true

[[redirects]]
  from = "/lynette"
  to = "https://us02web.zoom.us/j/3805633903?pwd=Um5OOWpuUnQwbCtuTHFRanRIZ1RQdz09"
  status = 301
  force = true

[[redirects]]
  from = "/kiera"
  to = "https://us02web.zoom.us/j/4642021059?pwd=Q1FhM1U2ZFc5WUpEMEtPWDgrM3cvQT09"
  status = 301
  force = true

